version: '3.8'
services: 
  db:
    build:
      context: ./mysql
    init: true
    restart: always
    ports: 
      - 3306:3306
    env_file: 
      - "./mysql/env/.env"
    volumes: 
      # conf
      - "./mysql/conf:/etc/mysql/conf.d"
      # data
      - "./mysql/data:/var/lib/mysql"
      # init
      - "./mysql/init:/docker-entrypoint-initdb.d"
  payara:
    image: payara/server-full:5.2021.5
    init: true
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
      - 4848:4848
    volumes: 
      # data
      - "./payara/data:/opt/payara/appserver/glassfish/domains/domain1/autodeploy"
      # lib
      - "./payara/lib/mysql-connector-java-8.0.22.jar:/opt/payara/appserver/glassfish/lib/mysql-connector-java-8.0.22.jar"
      # conf
      - "./payara/conf/domain.xml:/opt/payara/appserver/glassfish/domains/domain1/config/domain.xml"