version: '3.8'
services: 
  db:
    build:
      context: ./mysql
    restart: always
    ports: 
      - 3306:3306
    env_file: 
      - "./mysql/env/.env"
    volumes: 
      # conf
      - "./mysql/conf:/etc/mysql/conf.d"
      # data
      - "./mysql/data:/var/lib/mysql"
      # init
      - "./mysql/init:/docker-entrypoint-initdb.d"
